### ISSUE TITLE
Convert to reusable action: panel_plots

### ISSUE THREAD

**Issue by ccunningham101** [opensafely-actions/.github#3]
I'd like to convert my study into a reusable action. My study is in this repo:
[panel_plots](https://github.com/opensafely/antidepressant-prescribing-lda/blob/reformatting/analysis/panel_plots.py)

A common initial workflow for both research studies and curation efforts is to generate a panel of plots by demographic breakdowns over time. This is part 2 of that workflow which takes a joined measures file from [part 1](https://github.com/opensafely-actions/.github/issues/2) and generates a panel of plots from a user specified subset. Labels for the plots are automatically generated from the measures file name. Plots can be scaled to be either a rate or a percentage.

**Comment by iaindillingham** [comment]
Thanks for this 🙂. I've spoken to @inglesp, and we hope to be able to set aside some time during the next deck-scrubbing week[^1] to convert this scripted action to a reusable action. It's not quite as simple as "move a repo from `opensafely` to `opensafely-actions`", because we need to discuss versioning and the associated GitHub actions workflow.

[^1]: This will take place when Data Builder phase one is complete; see the pinned links in the [#team-data](https://bennettoxford.slack.com/archives/C03FB777L1M) Slack channel.

**Comment by iaindillingham** [comment]
Do you know whether this reusable action will work with ehrQL's measures framework, @ccunningham101? If not, then can you estimate how much time it would take to make it work? Cohort Extractor is not available for new projects, so we need not maintain backwards compatibility.

**Comment by ccunningham101** [comment]
I need to look into ehrQL a bit more to understand whether there is still useful code here. I can look and try to get you an answer by the end of the week. 
As-is, this code would not work in every situation due to a limitation of the measures framework we tried to work around
https://github.com/opensafely-actions/deciles-charts/issues/17

**Comment by iaindillingham** [comment]
Thanks, @ccunningham101. It would be really useful to know whether this is something we (the team!) should either work on or close. Please don't spend too long looking into erhQL -- just enough for a 🟢 or 🔴.

**Comment by ccunningham101** [comment]
Apologies I did not get to this last week. I think a reusable action to generate trend over time plots would be useful for dashboards (i.e. os interactive, rapid reports on the reports site) or the data curation phase of a project. I think it is unlikely a reusable action would have the flexibility needed for researcher publications.  

This could either be a single plot per measure (like the deciles chart), or have the option to choose a subset of measures and then group them into a panel plot (as was done here).
It might make sense to start fresh with the code, using this repo for ideas on command line args rather than copying this code, as 1) there is unnecessary complexity here in order to handle multiple groupbys 2) the opensafely python image matplotlib version has been updated

I estimate that a basic implementation would take ~2 days of work. 
I _might_ have time to help with implementation the second week of January but otherwise could try to give feedback/suggestions

**Comment by iaindillingham** [comment]
Thanks, @ccunningham101. I think that for the moment, we should close this issue. As there isn't an immediate request for panel plots, then before creating a new reusable action, we should undertake some discovery work to establish the use case more fully. Does that sound reasonable?

**Comment by ccunningham101** [comment]
Yes sounds reasonable
