### ISSUE TITLE
Convert to reusable action: convert svg image to png

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-actions/.github#4]
I'd like to convert my study into a reusable action. My study is in this repo:

https://github.com/opensafely/early-inflammatory-arthritis

[This script](https://github.com/opensafely/early-inflammatory-arthritis/blob/main/analysis/convert_images.py) converts all svg images within a given folder into png images.

This is useful within the context of OpenSAFELY because:

- Users have encountered problems outputting images from Stata actions as bitmaps.
- Bitmap images are required for reports that are hosted on [reports.opensafely](https://reports.opensafely.org/)
- Reports hosted on reports.opensafely currently have to be produced on the secure server (we can't produce a report locally and upload it). This means we can't convert images to be used in a report on the server or locally, using tools such as https://imagemagick.org/index.php

See [this slack thread](https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1653567741925379) for more detail.

Outside of the scope of reports.opensafely, it is also preferable that any image conversions happen as part of a reusable pipeline. Though this will likely require supporting more conversion formats.

**Comment by iaindillingham** [comment]
Thanks for this 🙂. I've spoken to @inglesp, and we hope to be able to set aside some time during the next deck-scrubbing week[^1] to convert this scripted action to a reusable action. It's not quite as simple as "move a repo from `opensafely` to `opensafely-actions`", because we need to discuss versioning and the associated GitHub actions workflow.

[^1]: This will take place when Data Builder phase one is complete; see the pinned links in the [#team-data](https://bennettoxford.slack.com/archives/C03FB777L1M) Slack channel.

**Comment by iaindillingham** [comment]
Hello @LFISHER7. Your study contains several actions, but I think you want to convert `analysis/convert_images.py` to a reusable action. If this is still the case, would you consider making a new repo for this action? As a minimum, the repo should contain `README.md` and `action.yaml`, as described in "[Developing reusable actions](https://docs.opensafely.org/actions-reusable/#developing-reusable-actions)".

You may have heard Simon talking about upcoming changes to [python-docker](https://github.com/opensafely-core/python-docker). Simon has yet to release his changes. You can find them on the [versioning](https://github.com/opensafely-core/python-docker/tree/versioning) branch.

Both v1 and v2 images have cairosvg as a direct dependency (i.e. cairosvg is listed in `requirements.in`). However, pinning your reusable action to the v2 image in `action.yaml` will ensure that your reusable action benefits from enhancements to the v2 image (and subsequent images) over the medium/long term. Consequently, you may wish to wait for Simon to release these upcoming changes before releasing your reusable action.

**Comment by LFISHER7** [comment]
Thanks for the update @iaindillingham. I'm going to close this as I don't think there's enough demand for this action to do any work on it. I'll reconsider the above if there is any future demand

**Comment by iaindillingham** [comment]
Thanks for letting me know, @LFISHER7.
