### ISSUE TITLE
Convert to reusable action

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-actions/.github#7]
I'd like to convert my study into a reusable action. My study is in this repo:

https://github.com/opensafely/project-dag

**Comment by iaindillingham** [comment]
Thanks, @LFISHER7. I've added this issue to the board. You can follow progress there.

**Comment by lucyb** [comment]
@sebbacon has suggested making this into a reusable GitHub Action that would be run whenever a project.yaml has changed. How would you both feel about that, would it be more useful there?

**Comment by iaindillingham** [comment]
That seems like a good idea. Where would we surface the diagram? (Or is that TBD?)

**Comment by LFISHER7** [comment]
Yes, that sounds good. I think the most useful place to surface it is in the readme, which I think means outputting the diagram as an image rather than md

**Comment by lucyb** [comment]
Could you just save it as a CI workflow artefact to start with? Would people know to look there?

**Comment by LFISHER7** [comment]
I don't think they would. If it isn't fully automated then I don't think there's sufficient value add over a reusable action

**Comment by lucyb** [comment]
Jon has also suggested this could be an option in the CLI. However, we've decided that we'll create the reusable action and use that to learn more about how we might use this feature in future.

**Comment by iaindillingham** [comment]
There's a short Slack thread.[^1]

[^1]: https://bennettoxford.slack.com/archives/C069SADHP1Q/p1708956506714339

**Comment by iaindillingham** [comment]
I've converted this to a reusable action, @LFISHER7. v0.0.1 was tagged automatically; for more information, please see [`DEVELOPERS.md`](https://github.com/opensafely-actions/project-dag/blob/main/DEVELOPERS.md).

**Comment by LFISHER7** [comment]
Thanks for doing this
